import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";

import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial learnt by Abdulmalik",
    template: "%s | Codevolution",
  },
  description: 'Generated by Next.js'
}


export default async function RootLayout({ 
  children, 
}: {
    children: React.ReactNode
  }) {
    await new Promise(resolve => {
        setTimeout(() => {
            resolve("Intentional Dealy")
        }, 1000)
    })
  return (
    <html lang="en">
      <body className="grid h-screen">
        <header className="bg-blue-200 text-2xl h-20 font-bold grid">
          <p className="justify-self-center self-center">EEE 202 Practice</p>
        </header>
        <div>
          {/* <ErrorWrapper> */}
            {children}
          {/* </ErrorWrapper> */}
        </div>
        <footer className="h-full bg-black text-white w-full text-2xl my-2 font-bold grid">
          <p className="justify-self-center self-center">Footer</p>
        </footer>
      </body>
    </html>
  )
}